# Generated by Django 2.1.3 on 2019-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20190224_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generator',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='generator',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=30),
        ),
    ]
