# Generated by Django 2.1.3 on 2019-02-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20190224_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='generator.Generator'),
        ),
    ]
