# Generated by Django 2.1.7 on 2019-03-11 06:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20190227_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='geo_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
