# Generated by Django 2.1.7 on 2019-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_generator_geo_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='palika_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
