# Generated by Django 2.1.7 on 2019-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_export_palika_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
