# Generated by Django 2.1.9 on 2019-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_auto_20190312_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='language',
            field=models.CharField(choices=[('en', 'English (Default)'), ('np', 'NEPALI')], default='en', max_length=30),
        ),
    ]
