sudo: required

language: generic

services:
  - docker

before_install:
  - curl https://s3.amazonaws.com/toggle-utils/docker_ci --output docker_ci && chmod +x docker_ci

  # Pull docker images
  - ./docker_ci pull

before_script:
  # Build server
  - ./docker_ci build

script:
  - echo 'TODO add test script here'

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./docker_ci push --on on_build
