sudo: required

language: generic

services:
    - docker

before_install:
    - docker pull ${DOCKER_IMAGE} || true
    - docker build --cache-from ${DOCKER_IMAGE} --tag ${DOCKER_IMAGE} .

before_script:
    - echo 'before_script'

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push ${DOCKER_IMAGE}
    - ./release_build.sh

env:
  global:
    - DOCKER_IMAGE='devtc/palika-profile:dev'
    - DOCKER_IMAGE_RC='devtc/palika-profile:latest'
