sudo: required

language: generic

services:
  - docker

before_install:
  - curl https://s3.amazonaws.com/toggle-utils/docker_ci --output docker_ci && chmod +x docker_ci

  - mkdir -p $REACT_STORE_DIR
  - git clone https://github.com/toggle-corp/react-store.git $REACT_STORE_DIR
  - git --git-dir=$REACT_STORE_DIR/.git --no-pager show --pretty=fuller --quiet
  - cp $REACT_STORE_DIR/stylesheets/_user-imports-sample.scss $REACT_STORE_DIR/stylesheets/_user-imports.scss

  # Pull docker images
  - ./docker_ci pull

before_script:
  # Build server
  - ./docker_ci build

script:
  - echo 'TODO add test script here'

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./docker_ci push --on on_build
  - if [ "${TRAVIS_BRANCH}" == "${RC_BRANCH}" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] ; then ./docker_ci push --on on_release; fi

env:
  global:
    - REACT_STORE_DIR=react-plugins/src/vendor/react-store
