version: '3.2'

services:
    db:
        image: postgres:9.5
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        volumes:
            - redis-data:/data

    server:
        image: palikaprofile/server:develop
        build:
          context: ./
          cache_from:
            - devtc/palika-profile:develop
        env_file:
            - .env
        command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
        volumes:
            - ./:/code
            # NOTE: DO NOT PUSH [THIS CHANGE]
            # - ..path_to_drafter/:/dep/drafter
            # - ..path_to_hrrp-maps:/dep/hrrp-maps
        ports:
            - '8008:8000'
        depends_on:
            - db
            - redis

    react-plugins:
        image: palikaprofile/react-plugins:develop
        build:
          context: ./react-plugins/
          cache_from:
            - devtc/palika-profile:react-plugins
        env_file:
            - .env
        command: sh -c 'yarn install && yarn start'
        volumes:
            - ./react-plugins/:/code
        ports:
            - '3008:3008'

volumes:
  postgres-data:
  redis-data:
