# Generated by Django 2.1.3 on 2019-02-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='shape_files/')),
                ('geo_type', models.CharField(choices=[('ward', 'Ward'), ('palika', 'Palika'), ('district', 'District')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='style_files/')),
                ('geoarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.GeoArea')),
            ],
        ),
    ]
