# Generated by Django 2.1.7 on 2019-03-13 12:25

import os
from django.db import migrations, models
from django.core.management import call_command
from django.core.files import File
from django.conf import settings
import django.db.models.deletion


def load_initial_districts(apps, schema_editor):
    call_command('loaddata', 'initial_geo.json', app_label='geo')


def upload_files(apps, schema_editor):
    GeoArea = apps.get_model('geo', 'GeoArea')
    GeoStyle = apps.get_model('geo', 'GeoStyle')

    for geoarea in GeoArea.objects.all():
        filename = geoarea.file.name
        filepath = os.path.join(settings.BASE_DIR, filename)
        with open(filepath, 'rb') as fp:
            geoarea.file = File(fp, filename.split('/')[-1])
            geoarea.save()

    for geostyle in GeoStyle.objects.all():
        filename = geostyle.file.name
        filepath = os.path.join(settings.BASE_DIR, filename)
        with open(filepath, 'rb') as fp:
            geostyle.file = File(fp, filename.split('/')[-1])
            geostyle.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(max_length=255, upload_to='shape_files/')
                ),
                (
                    'geo_type',
                    models.CharField(
                        choices=[('ward', 'Ward'), ('palika', 'Palika'), ('district', 'District')],
                        max_length=30, unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='GeoStyle',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255)),
                (
                    'file',
                    models.FileField(max_length=255, upload_to='style_files/')),
                (
                    'style_type',
                    models.CharField(
                        choices=[
                            ('district_style', 'District Style'),
                            ('palika_hide_style', 'Palika Hide Style'),
                            ('atlas_style', 'Atlas Style'),
                            ('ward_style', 'Ward Style'),
                            ('palika_en_style', 'Palika en Style'),
                            ('palika_np_style', 'Palika np Style'),
                        ],
                        max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palika',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255)),
                (
                    'code',
                    models.CharField(max_length=255, unique=True)),
                (
                    'district',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='geo.District',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='geo.Province',
            ),
        ),

        migrations.RunPython(load_initial_districts),
        migrations.RunPython(upload_files),
    ]
