# Generated by Django 2.1.3 on 2019-02-21 10:29
import os
from django.db import migrations
from django.core.management import call_command
from django.core.files import File
from django.conf import settings


def load_initial_districts(apps, schema_editor):
    call_command('loaddata', 'initial_geo.json', app_label='geo')


def upload_files(apps, schema_editor):
    GeoArea = apps.get_model('geo', 'GeoArea')
    GeoStyle = apps.get_model('geo', 'GeoStyle')

    for geoarea in GeoArea.objects.all():
        filename = geoarea.file.name
        filepath = os.path.join(settings.BASE_DIR, filename)
        with open(filepath, 'rb') as fp:
            geoarea.file = File(fp, filename.split('/')[-1])
            geoarea.save()

    for geostyle in GeoStyle.objects.all():
        filename = geostyle.file.name
        filepath = os.path.join(settings.BASE_DIR, filename)
        with open(filepath, 'rb') as fp:
            geostyle.file = File(fp, filename.split('/')[-1])
            geostyle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_districts),
        migrations.RunPython(upload_files),
    ]
