# Generated by Django 2.1.3 on 2019-02-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_load_initial_20190221_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarea',
            name='title',
        ),
    ]
