# Generated by Django 2.1.8 on 2019-06-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_initial_palika_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStyleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English (Default)'), ('np', 'NEPALI')], default='en', max_length=30, unique=True)),
                ('file', models.FileField(max_length=255, upload_to='style_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='geostyle',
            name='file',
        ),
        migrations.AlterField(
            model_name='geostyle',
            name='style_type',
            field=models.CharField(choices=[('district_style', 'District Style'), ('palika_hide_style', 'Palika Hide Style'), ('atlas_style', 'Atlas Style'), ('ward_style', 'Ward Style'), ('palika_style', 'Palika Style')], max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='geostylefile',
            name='geo_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.GeoStyle'),
        ),
    ]
