# Generated by Django 2.1.7 on 2019-03-12 05:15

from django.db import migrations
from django.core.management import call_command


def load_initial_districts(apps, schema_editor):
    call_command('loaddata', 'initial_palika.json', app_label='geo')


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20190312_0513'),
    ]

    operations = [
        migrations.RunPython(load_initial_districts),
    ]
