# Generated by Django 2.1.8 on 2019-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20190606_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geostylefile',
            name='language',
            field=models.CharField(choices=[('en', 'English (Default)'), ('np', 'NEPALI')], default='en', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='geostylefile',
            unique_together={('file', 'geo_style')},
        ),
    ]
