# Generated by Django 2.1.7 on 2019-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_initial_paliaka_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palika',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
